Repository JesseMellinger/Crate, pull requests merged in 2021-02, with the labels that each got.

#47 feature/web/profile edit form
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/user/EditUserInfo.js
  code/web/src/setup/routes/user.js
  code/web/src/setup/store.js
Labels: React, enhancement

#48 Feature/user profile
  code/web/src/modules/common/header/Header.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/UserAccount.js
  code/web/src/setup/routes/user.js
Labels: React, Sprint 1

#52 Feature/web/user nav bar
  code/web/src/modules/common/header/Header.js
  code/web/src/modules/user/EditUserInfo.js
  code/web/src/modules/user/UserAccount.js
  code/web/src/modules/user/common/UserMenu.js
  code/web/src/modules/user/common/UserMenu.test.js
  code/web/src/setup/routes/user.js
Labels: React, bug, enhancement

#60 Crate products
  code/api/package-lock.json
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/migrations/7-create-crate-product.js
  code/api/src/modules/crate-product/model.js
  code/api/src/modules/crate-product/mutations.js
  code/api/src/modules/crate-product/query.js
  code/api/src/modules/crate-product/resolvers.js
  code/api/src/modules/crate-product/tests/crateProductMutation.test.js
  code/api/src/modules/crate-product/tests/crateProductQuerys.test.js
  code/api/src/modules/crate-product/types.js
  code/api/src/modules/subscription-crate/mutations.js
  code/api/src/modules/subscription-crate/query.js
  code/api/src/modules/subscription-crate/resolvers.js
  code/api/src/modules/subscription-crate/tests/subscriptionCrateMutation.test.js
  code/api/src/modules/subscription-crate/tests/subscriptionCrateQuery.test.js
  code/api/src/modules/subscription/tests/subscriptionQuery.test.js
  code/api/src/modules/user/tests/userMutation.test.js
  code/api/src/modules/user/tests/userQuery.test.js
  code/api/src/seeders/1-user.js
  code/api/src/seeders/4-subscription.js
  code/api/src/seeders/5-subscription-crates.js
  code/api/src/seeders/6-crate-products.js
  code/api/src/setup/models.js
  code/api/src/setup/schema/mutations.js
  code/api/src/setup/schema/queries.js
  code/web/package-lock.json
  package-lock.json
Labels: Backend, Sprint 3

#61 Feature/web/add user info to new components
  code/api/src/seeders/1-user.js
  code/web/package-lock.json
  code/web/src/modules/user/EditUserInfo.js
  code/web/src/modules/user/UserAccount.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
Labels: React, Sprint 2, enhancement

#62 add cypress testing
  code/web/cypress.json
  code/web/cypress/fixtures/example.json
  code/web/cypress/integration/examples/user_test.js
  code/web/cypress/plugins/index.js
  code/web/cypress/support/commands.js
  code/web/cypress/support/index.js
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/user/EditUserInfo.js
  code/web/src/modules/user/UserAccount.js
Labels: Sprint 2, Sprint 3, Testing
